joint_impedance_example_controller:
    type: franka_example_controllers/JointImpedanceExampleController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    radius: 0.1
    acceleration_time: 2.0
    vel_max: 0.15
    publish_rate: 10.0
    coriolis_factor: 1.0



joint_impedance_trajectory_controller:
  type: franka_example_controllers/JointImpedanceExampleController/JointTrajectoryController
  arm_id: panda
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  k_gains:
    - 600.0
    - 600.0
    - 600.0
    - 600.0
    - 250.0
    - 150.0
    - 50.0
  d_gains:
    - 50.0
    - 50.0
    - 50.0
    - 20.0
    - 20.0
    - 20.0
    - 10.0
  radius: 0.1
  acceleration_time: 2.0
  vel_max: 0.15
  publish_rate: 10.0
  coriolis_factor: 1.0

  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05


effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  arm_id: panda
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  constraints:
    goal_time: 0.5
    panda_joint1:
      goal: 0.05
    panda_joint2:
      goal: 0.05
    panda_joint3:
      goal: 0.05
    panda_joint4:
      goal: 0.05
    panda_joint5:
      goal: 0.05
    panda_joint6:
      goal: 0.05
    panda_joint7:
      goal: 0.05
  gains:
    panda_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    panda_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    panda_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    panda_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}


franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  joint_names:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  arm_id: panda
